services:
  - type: web
    name: contact-book
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn contactbook_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: contact-book-db
          property: connectionString
    autoDeploy: true

databases:
  - name: contact-book-db
    databaseName: contact_book
    user: contact_book_user
